:root {
--primary-color: <?php echo esc_html(get_theme_mod('pr_color', '#379eff')); ?>;
--primary-hover-color: <?php echo esc_html(get_theme_mod('pr_h_color', '#081F46')); ?>;
--primary-bg-color: <?php echo esc_html(get_theme_mod('pr_bg_color', '#eef9ff')); ?>;
--footer-bg-color: <?php echo esc_html(get_theme_mod('f_bg_color', '#120d48')); ?>;
--primary-dark-color: <?php echo esc_html(get_theme_mod('pr_d_color', '#000000')); ?>;
--title-color: <?php echo esc_html(get_theme_mod('title_color', '#081F46')); ?>;
--fw-title-color: <?php echo esc_html(get_theme_mod('fw_title_color', '#ffffff')); ?>;
--price-color: <?php echo esc_html(get_theme_mod('price_color', '#081F46')); ?>;
--header-hover-color: <?php echo esc_html(get_theme_mod('header_h_color', '#eef9ff')); ?>;
--btn-bg-color-1: <?php echo esc_html(get_theme_mod('btn_bg_color_1', '#67b5ff')); ?>;
--btn-bg-color-2: <?php echo esc_html(get_theme_mod('btn_bg_color_2', '#4d86ff')); ?>;
--btn-hover-color: <?php echo esc_html(get_theme_mod('btn_h_color', '#379eff')); ?>;
--social-icon-txt-color: <?php echo esc_html(get_theme_mod('social_icon_txt_color', '#ffffff')); ?>;
--social-icon-color: <?php echo esc_html(get_theme_mod('social_icon_color', '#379eff')); ?>;
--social-icon-hover-color: <?php echo esc_html(get_theme_mod('social_icon_h_color', '#4d86ff')); ?>;
--woo-pr-fil-bg-color: <?php echo esc_html(get_theme_mod('woo_pr_fil_bg_color', '#379eff')); ?>;
--txt-select-bg-color: <?php echo esc_html(get_theme_mod('txt_select_bg_color', '#ecf4ff')); ?>;
--price-tile-color: <?php echo esc_html(get_theme_mod('price_tile_color', '#081F46')); ?>;
--sale-badge-bg-color: <?php echo esc_html(get_theme_mod('sale_badge_bg_color', '#379eff')); ?>;
--cart-count-color: <?php echo esc_html(get_theme_mod('cart_count_color', '#379eff')); ?>;
--success-icon-color: <?php echo esc_html(get_theme_mod('success_icon_color', '#379eff')); ?>;
}